### ISSUE TITLE
Add outputs to bsPopover() content

### ISSUE THREAD

**Issue by HelmeczyBruno** [lz100/spsComps#3]
Hi, 

Loving your package thus far.

I'd like to add reactive texts to spsComps::bsPopover()'s `content` argument.

Have tried passing said reactive text as textOutput() & htmlOutput() in the UI.

Also tried attaching it directly in the Server, but to no avail.

Hoping to hear from you soon.

Best,
Bruno

**Comment by lz100** [comment]
Could you provide a small reproducible example?

**Comment by lz100** [comment]
I am closing this issue due to no response.
