### ISSUE TITLE
gallery inside modalDialog enlarges only once

### ISSUE THREAD

**Issue by djorquerap** [lz100/spsComps#4]
I made a question in stackoverflow [here](https://stackoverflow.com/questions/75103467/spscomps-gallery-only-enlarges-once)
I got an app that opens up a `modalDialog `with an image inside a `spsComps::gallery`. However, the enlargement works only the first time the modal has been opened. How can this be fixed? Here is a minimal reprex: 

```
library(shiny)
library(spsComps)

ui <- fluidPage(
  actionButton("modal", "Open modal")
)

server <- function(input, output, session) {
  
  observeEvent(input$modal,
               {
                 showModal(modalDialog(
                   title = "test",
                   fluidRow(gallery(
                     texts = "", hrefs = "", image_frame_size = 6, 
                     images = "https://cdn.pixabay.com/photo/2018/07/31/22/08/lion-3576045__340.jpg",
                     enlarge = TRUE, title = "When you close this modal, the enlargement does not work again",
                     enlarge_method = "modal"
                   )),
                   footer = modalButton("Cerrar"),
                   easyClose = TRUE,
                   size = "xl"))
               })
  
}
shinyApp(ui, server)
```

**Comment by lz100** [comment]
Use a different method than Stackoverflow to address this, see [news](https://github.com/lz100/spsComps/blob/master/NEWS.md), and [64e6073](https://github.com/lz100/spsComps/commit/64e60731d31394d54cd0c8d3cdef3e9220270c71). No additional code required from users, just use the function as before. Now you can try the develop version.
