### ISSUE TITLE
cssLoader() does not work with local path src

### ISSUE THREAD

**Issue by nikolasharing** [lz100/spsComps#5]
I'm trying to get a custom loader to be used in cssLoader(). As used in the examples, this works:

```r
library(shiny)
spinner <- "https://github.com/lz100/spsComps/blob/master/examples/demo/www/spinner.gif?raw=true"
ui <- fluidPage(spsComps::cssLoader(type="gif", src = spinner))
server <- function(input, output, session) {}
shinyApp(ui, server)
```

While this does not: (local_spinner.gif lies in the current working directory)

```r
library(shiny)
ui <- fluidPage(spsComps::cssLoader(type="gif", src = "local_spinner.gif"))
server <- function(input, output, session) {}
shinyApp(ui, server)
```

**Comment by lz100** [comment]
This is not an issue with this package or Shiny. Reading tutorials on how to embed local resources in shinyApps will be helpful. Basically you need a `www` folder, and use `runApp()` on console instead. 

Suggested reading: 

- [stackOverflow post](https://stackoverflow.com/a/21998722/13002643), [another post](https://stackoverflow.com/a/69620738/13002643)
- help file of `addResourcePath`
