### ISSUE TITLE
Can't make popups work with anything else but action button

### ISSUE THREAD

**Issue by nfuryn** [lz100/spsComps#6]
Basically attempting to show popups on each observation in a RenderTable, but I am getting a variety of errors, including "number of items to replace is not a multiple of replacement length", "Inherits(tag, "shiny.tag") not TRUE", "Invalid icon. Use Shiny's 'icon()' function to generate a valid icon" and many more. The latter you can see in the code below. I have tried with html span tags and a multitude of other options.

```
ui <- fluidPage(
    tags$div(tableOutput('table_popover'))
)

server <- function(input, output, session) {

  convert <- function(name, surname) {
    link <- paste0('<a href="#" onclick="Shiny.setInputValue(\'sp\', \'', name, '\'); Shiny.setInputValue(\'sd\', \'', surname, '\');">', name, '</a>') %>% bsPopover(HTML("<s>del content</s>"), html = TRUE, bgcolor = "#d9534f")
    link
  }
  table_pop <- data.frame(name = c("diego", "ismail"),
                          surname = c("rodriguez", "khan"),
                          three = c(3, 6),
                          four = c(4, 8))
  output$table_popover <- renderTable({
    table_pops <- table_pop
    
    for (i in 1:nrow(table_pops)) {
        table_pops[i, 1] <- convert(table_pops$name[i], table_pops$surname[i])
    }
    
    table_pops
  }, sanitize.text.function = function(x) x)
}```

**Comment by lz100** [comment]
Out of town, take a look in a few weeks

**Comment by nfuryn** [comment]
> Out of town, take a look in a few weeks

I was wondering if there's any news? :) to add to this, this is me trying to popovers in server.

**Comment by lz100** [comment]
Your code is not reproducible, I can't run the code you posted. 

Maybe read [this](https://github.com/rstudio/shiny/wiki/Creating-a-Reproducible-Example) and edit the code.

Just let you know, without running the code, I can already tell the way you use icon is incorrect and is not related to this package. Please refer to the `icon` help file in Shiny on how to use it.

**Comment by nfuryn** [comment]
> Your code is not reproducible, I can't run the code you posted.
> 
> Maybe read [this](https://github.com/rstudio/shiny/wiki/Creating-a-Reproducible-Example) and edit the code.
> 
> Just let you know, without running the code, I can already tell the way you use icon is incorrect and is not related to this package. Please refer to the `icon` help file in Shiny on how to use it.
```

ui <- fluidPage(
    tags$div(tableOutput('table_popover'))
)

server <- function(input, output, session) {

  convert <- function(name, surname) {
    link <- paste0('<a href="#" onclick="Shiny.setInputValue(\'sp\', \'', name, '\'); Shiny.setInputValue(\'sd\', \'', surname, '\');">', name, '</a>') %>% bsPopover(HTML("<s>del content</s>"), html = TRUE, bgcolor = "#d9534f")
    link
  }
  table_pop <- data.frame(name = c("diego", "ismail"),
                          surname = c("rodriguez", "khan"),
                          three = c(3, 6),
                          four = c(4, 8))
  output$table_popover <- renderTable({
    table_pops <- table_pop
    
    for (i in 1:nrow(table_pops)) {
        table_pops[i, 1] <- convert(table_pops$name[i], table_pops$surname[i])
    }
    
    table_pops
  }, sanitize.text.function = function(x) x)
}
```

**Comment by lz100** [comment]
```r
library(magrittr)
library(spsComps)
library(shiny)
ui <- fluidPage(
    spsDepend("pop-tip"),
    tags$div(tableOutput('table_popover'))
)

server <- function(input, output, session) {
    
    convert <- function(name, surname) {
        link <- tags$a(
                href="#",
                onclick="Shiny.setInputValue(\'sp\', \'', name, '\'); Shiny.setInputValue(\'sd\', \'', surname, '\');",
                name
            ) %>% 
            bsPopover(tag = ., HTML("<s>del content</s>"), html = TRUE, bgcolor = "#d9534f")
        link
    }
    table_pop <- data.frame(name = c("diego", "ismail"),
                            surname = c("rodriguez", "khan"),
                            three = c(3, 6),
                            four = c(4, 8))
    output$table_popover <- renderTable({
        table_pops <- table_pop
        
        for (i in 1:nrow(table_pops)) {
            table_pops[i, 1] <- convert(table_pops$name[i], table_pops$surname[i]) %>% as.character()
        }
        
        table_pops
    }, sanitize.text.function = function(x) x)
}

shinyApp(ui, server)
```

- `bsPopover` only accept shiny tags objects. You are using character, this is not allowed. You can use the `a` tag directly to create your element instead of `paste`.
- To have HTML work inside a table, you need to paste the shiny tag back to character. I know it's complicated why we convert text to shiny tag then convert back to text. This is how shiny works. 
- Since it's character inside the dataframe, the HTML dependencies are removed from the shiny tag. We need to append it manually. You can easily do this in `spsComps` with `spsDepend`.

Nothing need to change with the package. Just some shiny mechanisms you need to know better. Keep learning.

**Comment by nfuryn** [comment]
> Nothing need to change with the package. Just some shiny mechanisms you need to know better. Keep learning.

Thank you, this works! Definitely. But can you tell me the class of bspopover? I wanted to implement [this ](https://stackoverflow.com/questions/15989591/how-can-i-keep-bootstrap-popovers-alive-while-being-hovered) but I was not able to figure out the class, and bspopover doesn't take class either.

**Comment by lz100** [comment]
Thanks for bringing my attention. This is a good feature that I will support. Please wait for my updates.

**Comment by lz100** [comment]
New option `click_inside` added in [e03a0d9](https://github.com/lz100/spsComps/commit/e03a0d9e7413b7fc1bcb0ee2427abea40a4837b5). You can try the shinyapp.io demo first, I have updated that. Please wait for one day for CRAN to process the new version.
